### ISSUE TITLE
Cannot access to the data in Google Drive

### ISSUE THREAD

**Issue by zxydi1992** [Wakeupbuddy/amodalAPI#9]
It says access denied and I wonder if there are any ways to download the annotation files.

**Comment by zxydi1992** [comment]
I figured out, and downloaded data.

**Comment by egeozguroglu** [comment]
Hi @zxydi1992, how were you able to download it? Same issue.

**Comment by hzkgit** [comment]
http://images.cocodataset.org/annotations/annotations_trainval2014.zip

**Comment by hzkgit** [comment]
i am not sure whether it is matched
